name: release
on:
  push:
    branches:
      - main
jobs:
  Build-Artifacts:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: [1.11.4]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Use Deno version
        uses: denoland/setup-deno@v1
        with:
          deno-version: "1.11.4"
          is-canary: false
      - name: Test
        run: bash tools/test.sh
      # - name: Compile
      #   run: |
      #     echo $DENO_CANARY
      #     DENO_CANARY=false
      #     bash tools/compile.sh
      # - name: Upload release to GitHub
      #   uses: softprops/action-gh-release@v1
      #   if: |
      #     github.repository == 'mtso/obi' &&
      #     startsWith(github.ref, 'refs/tags/')
      #   with:
      #     # build/obi-x86_64-pc-windows-msvc
      #     # build/obi-x86_64-apple-darwin
      #     # build/obi-aarch64-apple-darwin
      #     files: |
      #       build/obi-x86_64-unknown-linux-gnu
      #       build/obi-x86_64-pc-windows-msvc
      #       build/obi-x86_64-apple-darwin
      #       build/obi-aarch64-apple-darwin
      #     draft: true
      #     token: ${{ secrets.GITHUB_TOKEN }}
